name: voting-app

services:
  vote:
    public: true
    build: vote
    replicas: 2
    ports:
      - 8080

  redis:
    image: redis
    ports:
      - 6379
    volumes:
      - redis:/data

volumes:
  redis:
    size: 1Gi
